version: '2'
services:
        apache2:
                image: httpd
                ports:
                        - 80:80
                volumes:
                        - .:/usr/local/apache2/htdocs/
